#!/bin/bash

set -e

if [ "$1" == "-c" -o "$1" == "zfs" ] ; then
	shift
	exec "$0" $@
fi

export PATH=/sbin:/usr/sbin:/usr/local/sbin:"$PATH"

cmd="$1"

if [ "$cmd" == "snapshot" -o "$cmd" == "list" -o "$cmd" == "recv" -o "$cmd" == "receive" -o "$cmd" == "send" -o "$cmd" == "destroy" -o "$cmd" == "get" ] ; then
	# FIXME: verify that the name of the snapshot contains an @
	sudo zfs "$@"
	exit $?
fi

echo "usage: zfs-shell [ list | snapshot | send | recv | receive | destroy | get ] <snapshotname>" >&2
exit 64
