#!/bin/bash

set -e

if [ "$1" == "-c" ] ; then
	shift
	exec "$0" $@
fi

export PATH=/sbin:/usr/sbin:/usr/local/sbin:"$PATH"

cmd="$1"

if [ "$cmd" == "recv" ] ; then
	shift

	if [ "$1" != "" ]
	then
		sudo zfs recv "$@"
		exit 0
	fi
elif [ "$cmd" == "destroy" ] ; then
	shift

	if [ "$1" != "" ]
	then
		sudo zfs destroy "$@"
		exit 0
	fi
elif [ "$cmd" == "list" ] ; then
	shift

	if [ "$1" == "" ]
	then
		sudo zfs list "$@"
		exit 0
	fi
fi

echo "usage: zfsrecvsh recv [-v] <snapshotname>" >&2
exit 64
